#!/usr/bin/env python3
import argparse, pathlib, subprocess, sys
from krypt.parser import Parser
from krypt.runtime import run_source

KRYPT_VERSION = '0.1.0'
KRYPT_ABOUT = 'Krypt: linguagem experimental com runtime gráfico próprio.'

def compile_file(src, out):
    source_path=pathlib.Path(src).resolve(); source=source_path.read_text(encoding='utf-8'); Parser(source).parse()
    out=pathlib.Path(out); out.parent.mkdir(parents=True,exist_ok=True)
    escaped=repr(source)
    project_root=pathlib.Path(__file__).resolve().parent
    out.write_text(f"# Generated by Krypt compiler\nimport sys, pathlib\nsys.path.insert(0, {str(project_root)!r})\nfrom krypt.runtime import run_source\nrun_source({escaped}, pathlib.Path({str(source_path.parent)!r}))\n",encoding='utf-8')
    return out

def main():
    p=argparse.ArgumentParser(prog='krypt',description='Compilador e executor da linguagem Krypt')
    p.add_argument('-File', '--file', dest='file', help='executa um arquivo .krypt')
    p.add_argument('--version', action='version', version=f'Krypt {KRYPT_VERSION}')
    p.add_argument('--about', action='version', version=f'Krypt {KRYPT_VERSION}\n{KRYPT_ABOUT}')
    sub=p.add_subparsers(dest='cmd')
    r=sub.add_parser('run',help='executa um arquivo .krypt'); r.add_argument('source')
    h=sub.add_parser('help',help='mostra esta ajuda'); h.set_defaults(show_help=True)
    k=sub.add_parser('check',help='verifica a sintaxe sem executar'); k.add_argument('source')
    c=sub.add_parser('compile',help='gera Python intermediário'); c.add_argument('source'); c.add_argument('-o','--output')
    b=sub.add_parser('build',help='gera executável via PyInstaller'); b.add_argument('source'); b.add_argument('-n','--name')
    args=p.parse_args()
    try:
        if args.file:
            target=pathlib.Path(args.file).resolve(); run_source(target.read_text(encoding='utf-8'),target.parent)
        elif getattr(args,'show_help',False):
            p.print_help()
        elif args.cmd=='check':
            Parser(pathlib.Path(args.source).read_text(encoding='utf-8')).parse(); print(f'Sintaxe OK: {args.source}')
        elif not args.cmd:
            p.print_help(); return 2
        elif args.cmd=='run':
            target=pathlib.Path(args.source).resolve(); run_source(target.read_text(encoding='utf-8'),target.parent)
        elif args.cmd=='compile':
            out=args.output or str(pathlib.Path(args.source).with_suffix('.py')); print(f'Compilado: {compile_file(args.source,out)}')
        else:
            name=args.name or pathlib.Path(args.source).stem; generated=compile_file(args.source,f'build/{name}.py')
            cmd=[sys.executable,'-m','PyInstaller','--clean','--noconfirm','--onefile','--name',name,'--paths','.', '--hidden-import','tkinter','--hidden-import','_tkinter',str(generated)]
            print('Executando:', ' '.join(cmd)); subprocess.run(cmd,check=True); print(f'Executável criado em dist/{name}')
    except Exception as e:
        print(f'Krypt error: {e}',file=sys.stderr); return 1
    return 0
if __name__=='__main__': raise SystemExit(main())
